// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_txtWallet = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_txtBalance = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_txtConnect = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_Label29 = NULL;
// event funtions
void ui_event_Screen4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 100, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label22 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -48);
    lv_obj_set_y(ui_Label22, -40);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Wallet:");

    ui_txtWallet = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_txtWallet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtWallet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtWallet, 30);
    lv_obj_set_y(ui_txtWallet, -40);
    lv_obj_set_align(ui_txtWallet, LV_ALIGN_CENTER);

    ui_Label24 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -49);
    lv_obj_set_y(ui_Label24, -12);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "Balance:");

    ui_txtBalance = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_txtBalance, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtBalance, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtBalance, 20);
    lv_obj_set_y(ui_txtBalance, -12);
    lv_obj_set_align(ui_txtBalance, LV_ALIGN_CENTER);

    ui_txtConnect = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_txtConnect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtConnect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtConnect, -1);
    lv_obj_set_y(ui_txtConnect, 23);
    lv_obj_set_align(ui_txtConnect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtConnect, "Connect to server");

    ui_Button5 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button5, 73);
    lv_obj_set_height(ui_Button5, 27);
    lv_obj_set_x(ui_Button5, 3);
    lv_obj_set_y(ui_Button5, 62);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label28 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, -2);
    lv_obj_set_y(ui_Label28, -83);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "Connection");

    ui_Label29 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, 3);
    lv_obj_set_y(ui_Label29, 62);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "Sync");

    lv_obj_add_event_cb(ui_Screen4, ui_event_Screen4, LV_EVENT_ALL, NULL);

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_Label22 = NULL;
    ui_txtWallet = NULL;
    ui_Label24 = NULL;
    ui_txtBalance = NULL;
    ui_Label26 = NULL;
    ui_txtConnect = NULL;
    ui_Button5 = NULL;
    ui_Label28 = NULL;
    ui_Label29 = NULL;

}
