// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_txtWallet;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_txtBalance;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_txtConnect;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label29;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

