// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_txtFood = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_txtEnery = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_btnFeed = NULL;
lv_obj_t * ui_btnPlay = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label14 = NULL;
// event funtions
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -50);
    lv_obj_set_y(ui_Label8, -27);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Food:");

    ui_txtFood = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_txtFood, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtFood, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtFood, 2);
    lv_obj_set_y(ui_txtFood, -28);
    lv_obj_set_align(ui_txtFood, LV_ALIGN_CENTER);

    ui_Label10 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -56);
    lv_obj_set_y(ui_Label10, 15);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Energy:");

    ui_txtEnery = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_txtEnery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtEnery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtEnery, 4);
    lv_obj_set_y(ui_txtEnery, 17);
    lv_obj_set_align(ui_txtEnery, LV_ALIGN_CENTER);

    ui_Label12 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -4);
    lv_obj_set_y(ui_Label12, -70);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Items");

    ui_btnFeed = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_btnFeed, 46);
    lv_obj_set_height(ui_btnFeed, 23);
    lv_obj_set_x(ui_btnFeed, 65);
    lv_obj_set_y(ui_btnFeed, -27);
    lv_obj_set_align(ui_btnFeed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnFeed, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnFeed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnPlay = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_btnPlay, 46);
    lv_obj_set_height(ui_btnPlay, 21);
    lv_obj_set_x(ui_btnPlay, 64);
    lv_obj_set_y(ui_btnPlay, 16);
    lv_obj_set_align(ui_btnPlay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnPlay, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnPlay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 63);
    lv_obj_set_y(ui_Label13, -27);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Feed");

    ui_Label14 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 64);
    lv_obj_set_y(ui_Label14, 15);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Play");

    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Label8 = NULL;
    ui_txtFood = NULL;
    ui_Label10 = NULL;
    ui_txtEnery = NULL;
    ui_Label12 = NULL;
    ui_btnFeed = NULL;
    ui_btnPlay = NULL;
    ui_Label13 = NULL;
    ui_Label14 = NULL;

}
