// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_arcStep = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_btnClaimCount = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_txtStep = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Label20 = NULL;
// event funtions
void ui_event_Screen3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_arcStep = lv_arc_create(ui_Screen3);
    lv_obj_set_width(ui_arcStep, 150);
    lv_obj_set_height(ui_arcStep, 150);
    lv_obj_set_x(ui_arcStep, 0);
    lv_obj_set_y(ui_arcStep, -6);
    lv_obj_set_align(ui_arcStep, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arcStep, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_arcStep, 50);

    ui_Label16 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -2);
    lv_obj_set_y(ui_Label16, 57);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Step count");

    ui_btnClaimCount = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_btnClaimCount, 74);
    lv_obj_set_height(ui_btnClaimCount, 29);
    lv_obj_set_x(ui_btnClaimCount, 1);
    lv_obj_set_y(ui_btnClaimCount, 87);
    lv_obj_set_align(ui_btnClaimCount, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnClaimCount, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnClaimCount, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -2);
    lv_obj_set_y(ui_Label17, 86);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Claim");

    ui_txtStep = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_txtStep, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtStep, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtStep, -21);
    lv_obj_set_y(ui_txtStep, -9);
    lv_obj_set_align(ui_txtStep, LV_ALIGN_CENTER);

    ui_Label19 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 10);
    lv_obj_set_y(ui_Label19, -8);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "/");

    ui_Label20 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 32);
    lv_obj_set_y(ui_Label20, -8);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "1000");

    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_arcStep = NULL;
    ui_Label16 = NULL;
    ui_btnClaimCount = NULL;
    ui_Label17 = NULL;
    ui_txtStep = NULL;
    ui_Label19 = NULL;
    ui_Label20 = NULL;

}
