// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_txtFood;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_txtEnery;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_btnFeed;
extern lv_obj_t * ui_btnPlay;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

